server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: insta
    password: bitc5600
    
    # 스프링에서 머스태치 세션 적용하려면 필요
  mustache:
    expose-session-attributes: true
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true  
      hibernate.format_sql: true
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  security: # test용 security 로그인 아이디, 비밀번호 지정
    user:
      name: cos
      password: 1234
      
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1176498252715446
            client-secret: 006f6435a2343bb6845c4ee7dbf43330
            scope:
            - email
            - public_profile
      
cos: # like 변수, 자바에서 찾기 쉽게 커스텀
  secret: 홍차

file: # 파일 저장시 경로 
  path: C:/src/jwtoauthwork/instagram/upload/
